[package]
name = "git-lfs-spec"
version = "0.1.0"
authors = ["Sameer Puri <crates@purisa.me>"]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
url = "1"
url_serde = "0"
chrono = { version = "0", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "0"
serde_json = "1"
