[package]
name = "git-lfs-ipfs-cli"
version = "0.1.0"
authors = ["Sameer Puri <purisame@spuri.io>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
actix = "0.7"
serde_json = "1.0"
futures = "0.1.25"
failure = "0.1"
env_logger = "0.6"
bytes = "0.4"
cid = "0.3" 
git-lfs-spec = { path = "../git-lfs-spec", version = "0.1" }
clap = "2.32"
multihash = "0.8"
ipfs-api = { version = "0.5.0-alpha2", git = "https://github.com/ferristseng/rust-ipfs-api", features = ["actix"], default-features = false }
hex = "0.3"
url = "1.7"
lazy_static = "1.2"
serde = "1.0"
publicsuffix = "1.5"
path-clean = "0.1"

[dev-dependencies]
pretty_assertions = "0.5"
